rl:
  api_url: 'https://risu.life/api'
  access_token: superadminaccesstoken

amqp:
  url: 'amqp://guest:guest@127.0.0.1/'
  client_properties:

storage:
  current_storage: s3

  replays_path: 'dev_replays'
  beatmaps_path: 'dev_beatmaps'

  s3:
    region_name: 'ru-1a'

    secret_access_key: minioadmin
    access_key_id: minioadmin

    endpoint_url: 'http://127.0.0.1:9000'
