# coding: utf-8

"""
    RL API Internal

    Internal API endpoint, requires `internal.\\*.\\*` scope  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Error(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error_id': 'str',
        'error_description': 'str',
        'message': 'str'
    }

    attribute_map = {
        'error_id': 'error_id',
        'error_description': 'error_description',
        'message': 'message'
    }

    def __init__(self, error_id=None, error_description=None, message=None):  # noqa: E501
        """Error - a model defined in Swagger"""  # noqa: E501
        self._error_id = None
        self._error_description = None
        self._message = None
        self.discriminator = None
        self.error_id = error_id
        self.error_description = error_description
        self.message = message

    @property
    def error_id(self):
        """Gets the error_id of this Error.  # noqa: E501


        :return: The error_id of this Error.  # noqa: E501
        :rtype: str
        """
        return self._error_id

    @error_id.setter
    def error_id(self, error_id):
        """Sets the error_id of this Error.


        :param error_id: The error_id of this Error.  # noqa: E501
        :type: str
        """
        if error_id is None:
            raise ValueError("Invalid value for `error_id`, must not be `None`")  # noqa: E501

        self._error_id = error_id

    @property
    def error_description(self):
        """Gets the error_description of this Error.  # noqa: E501


        :return: The error_description of this Error.  # noqa: E501
        :rtype: str
        """
        return self._error_description

    @error_description.setter
    def error_description(self, error_description):
        """Sets the error_description of this Error.


        :param error_description: The error_description of this Error.  # noqa: E501
        :type: str
        """
        if error_description is None:
            raise ValueError("Invalid value for `error_description`, must not be `None`")  # noqa: E501

        self._error_description = error_description

    @property
    def message(self):
        """Gets the message of this Error.  # noqa: E501


        :return: The message of this Error.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this Error.


        :param message: The message of this Error.  # noqa: E501
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Error, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Error):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
