# coding: utf-8

"""
    RL API Internal

    Internal API endpoint, requires `internal.\\*.\\*` scope  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateScoreRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'replay_id': 'int',
        'user_id': 'int',
        'parsed': 'UpdateScoreRequestParsed'
    }

    attribute_map = {
        'replay_id': 'replay_id',
        'user_id': 'user_id',
        'parsed': 'parsed'
    }

    def __init__(self, replay_id=None, user_id=None, parsed=None):  # noqa: E501
        """UpdateScoreRequest - a model defined in Swagger"""  # noqa: E501
        self._replay_id = None
        self._user_id = None
        self._parsed = None
        self.discriminator = None
        self.replay_id = replay_id
        self.user_id = user_id
        self.parsed = parsed

    @property
    def replay_id(self):
        """Gets the replay_id of this UpdateScoreRequest.  # noqa: E501


        :return: The replay_id of this UpdateScoreRequest.  # noqa: E501
        :rtype: int
        """
        return self._replay_id

    @replay_id.setter
    def replay_id(self, replay_id):
        """Sets the replay_id of this UpdateScoreRequest.


        :param replay_id: The replay_id of this UpdateScoreRequest.  # noqa: E501
        :type: int
        """
        if replay_id is None:
            raise ValueError("Invalid value for `replay_id`, must not be `None`")  # noqa: E501

        self._replay_id = replay_id

    @property
    def user_id(self):
        """Gets the user_id of this UpdateScoreRequest.  # noqa: E501


        :return: The user_id of this UpdateScoreRequest.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this UpdateScoreRequest.


        :param user_id: The user_id of this UpdateScoreRequest.  # noqa: E501
        :type: int
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def parsed(self):
        """Gets the parsed of this UpdateScoreRequest.  # noqa: E501


        :return: The parsed of this UpdateScoreRequest.  # noqa: E501
        :rtype: UpdateScoreRequestParsed
        """
        return self._parsed

    @parsed.setter
    def parsed(self, parsed):
        """Sets the parsed of this UpdateScoreRequest.


        :param parsed: The parsed of this UpdateScoreRequest.  # noqa: E501
        :type: UpdateScoreRequestParsed
        """
        if parsed is None:
            raise ValueError("Invalid value for `parsed`, must not be `None`")  # noqa: E501

        self._parsed = parsed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateScoreRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateScoreRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
